---
title: "Protected Species Division Open Science"
subtitle: "A hub for PSDOS datasets, tools, and resources"
page-layout: full
---

The [Protected Species Division (PSD)](https://www.fisheries.noaa.gov/pacific-islands/science-data/providing-science-protect-marine-species) of the [Pacific Islands Fisheries Science Center](https://www.fisheries.noaa.gov/about/pacific-islands-fisheries-science-center) provides the scientific foundation for the conservation of cetaceans, Hawaiian monk seals, and sea turtles in the Pacific Islands, guided by mandates of the Marine Mammal Protection Act, Endangered Species Act, and international agreements.

Members of PSD have joined the growing [NMFS Open Science](https://nmfs-opensci.github.io/) community through participation in [NMFS Openscapes](https://nmfs-openscapes.github.io/) training. As in other scientific fields, [open science](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2020EA001562) practices can advance protected species science by making it more accessible, transparent, and reproducible. This site will serve as a hub for PSD Open Science (PSDOS), where we will aggregate links to our datasets, analytical tools, and other resources for ourselves, our collaborators and stakeholders, and other researchers and analysts. 

The PSDOS hub is a work in progress that we intend to grow and develop in the months and years to come. If you have suggestions for resources or other information to include, please let us know by [creating an issue](https://github.com/PIFSC-Protected-Species-Division/PSDOS/issues) in the PSDOS repository.

## PSD Resources

-   [Git Started](https://github.com/sfregosi/CRPTools) - *New to GitHub, start here for help*
-   [PSD staff publications](https://apps-pifsc.fisheries.noaa.gov/library/staff_publications.php?division=psd&doc_type=all) - *Compiled by NOAA libraries*
-   *More TBD...*

## NMFS Resources

-   [NMFS Open Science](https://nmfs-opensci.github.io/) - *Includes an incredible resource book, a NMFS GitHub SOP, and GitHub repo templates*
-   [NMFS Openscapes](https://nmfs-openscapes.github.io/) - *Describes the multi-year collaboration between NMFS and Openscapes*
-   [NOAA Fisheries Integrated Toolbox](https://noaa-fisheries-integrated-toolbox.github.io/) - *A portal of operational tools for a variety of applications, including protected species assessment*
-   [NOAA Fisheries Integrated Modeling System](https://noaa-fims.github.io/) - *A software system to support next-generation fisheries stock assessment*
-   [NMFS R User Group](https://nmfs-opensci.github.io/NMFS-R-UG/) - *Connect with over 200 NMFS R users*
-   *More TBD...*
